# ==================================================================================
#       Copyright (c) 2019-2020 Nokia
#       Copyright (c) 2018-2020 AT&T Intellectual Property.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# ==================================================================================
FROM python:3.8-alpine

# copy rmr libraries from builder image in lieu of an Alpine package
#COPY --from=nexus3.o-ran-sc.org:10002/o-ran-sc/bldr-alpine3-rmr:4.5.2 /usr/local/lib64/librmr* /usr/local/lib64/

# RMR setup
RUN mkdir -p /opt/route/
COPY routing_table.rt test_route_thrd.rt
ENV LD_LIBRARY_PATH /usr/local/lib/:/usr/local/lib64
#ENV RMR_SEED_RT /opt/route/test_route.rt
ENV RMR_LOG_VLEVEL 0
ENV RMR_RTG_SVC -1
#ENV RMR_RTREQ_FREQ 60

# sdl needs gcc
RUN apk update && apk add gcc musl-dev bash

# Install
RUN pip install --upgrade pip
RUN pip install ricxappframe==3.0.2
#RUN apk add valgrind

COPY ricxappframe .
COPY rmr ./usr/local/lib/python3.8/site-packages/ricxappframe/rmr
COPY lib64 ./usr/local/lib64
COPY submgr.py .

# Run
ENV PYTHONUNBUFFERED 2
CMD python3.8 submgr.py
#CMD valgrind --tool=memcheck --leak-check=full python3.8 submgr.py
