apiVersion: v1
kind: Pod
metadata:
  name: e2mgr-pod
  labels:
    app: e2mgr-webserver
spec:
  nodeName: lienlab305-virtualbox # schedule pod to specific node
  containers:
  - name: e2mgr
    image: e2mgryaml6:release
    
    #command: ["./test616"]
    env:
     - name: RMR_SEED_RT
       value: test_route_thrd.rt
     - name: DEMO
       value: "123"
       #command: ["./test616"]
    #ports:
    #- containerPort: 4563
  hostNetwork: true
---
apiVersion: v1
kind: Service
metadata:
  name: e2mgr-service
spec:
  type: NodePort
  ports:
    - port: 4200
      #targetPort: 4563
      #nodePort: 30420
      #30400
  selector:
    app: e2mgr-webserver  
